- id: '1770990019738'
  alias: Send Lock originator to Loxone
  description: ''
  use_blueprint:
    path: mine/loxone_inputs.yaml
    input:
      target_entities:
      - sensor.dach_links_priority_lock_originator
      - sensor.dach_rechts_priority_lock_originator
- id: '1771331444049'
  alias: Send lock timer to loxone
  description: ''
  use_blueprint:
    path: mine/loxone_inputs.yaml
    input:
      target_entities:
      - sensor.dach_links_priority_lock_timer
      - sensor.dach_rechts_priority_lock_timer
      value_template: '{% if value == ''unknown'' %}0{% else %}{{ value }}{% endif
        %}'
- id: '1771360145720'
  description: Forces an update of slat position and lock originator in case there
    is a lock every 10 minutes unless the slats move or the lock gets updated. The
    purpose is to have a lock indicator that is not stale, which it otherwise would
    be.
  triggers:
  - trigger: time_pattern
    minutes: /10
  - trigger: homeassistant
    event: start
  conditions:
  - condition: template
    value_template: "{% set entities = [\n  states.sensor.dach_links_priority_lock_originator,\n
      \ states.sensor.dach_links_priority_lock_timer,\n  states.cover.dach_links\n]
      %} {# Filter the list to see if any entity was updated LESS than 15 minutes
      ago #} {{ entities | selectattr('last_updated', 'gt', now() - timedelta(minutes=5))
      | list | count == 0 }}\n"
  actions:
  - action: cover.stop_cover_tilt
    target:
      entity_id: cover.dach_links
- id: '1771361016291'
  alias: 'Inactivity Watchdog: Dach Rechts'
  description: Forces an update of slat position and lock originator in case there
    is a lock every 10 minutes unless the slats move or the lock gets updated. The
    purpose is to have a lock indicator that is not stale, which it otherwise would
    be.
  triggers:
  - trigger: time_pattern
    minutes: /10
  - trigger: homeassistant
    event: start
  conditions:
  - condition: template
    value_template: "{% set entities = [\n  states.sensor.dach_rechts_priority_lock_originator,\n
      \ states.sensor.dach_rechts_priority_lock_timer,\n  states.cover.dach_rechts\n]
      %} {# Filter the list to see if any entity was updated LESS than 15 minutes
      ago #} {{ entities | selectattr('last_updated', 'gt', now() - timedelta(minutes=5))
      | list | count == 0 }}\n"
  actions:
  - action: cover.stop_cover_tilt
    target:
      entity_id: cover.dach_rechts
- id: '1771534982149'
  alias: Dach tilt to Loxone
  description: ''
  use_blueprint:
    path: mine/loxone_inputs.yaml
    input:
      target_entities:
      - cover.dach_links
      - cover.dach_rechts
      attribute_name: current_tilt_position
      value_template: '{{ value }}'
- id: '1771748333394'
  alias: 'Dach Links: update state when lock originator changes'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.dach_links_priority_lock_originator
  conditions: []
  actions:
  - action: cover.stop_cover_tilt
    metadata: {}
    data: {}
    target:
      entity_id: cover.dach_links
  mode: single
- id: '1771748414999'
  alias: 'Dach Rechts: Update state when lock originator changes'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.dach_rechts_priority_lock_originator
  conditions: []
  actions:
  - action: cover.stop_cover_tilt
    metadata: {}
    data: {}
    target:
      entity_id: cover.dach_rechts
  mode: single
