- id: '1770990019738'
  alias: Send Lock originator to Loxone
  description: ''
  use_blueprint:
    path: mine/loxone_inputs.yaml
    input:
      target_entities:
      - sensor.dach_links_priority_lock_originator
      - sensor.dach_rechts_priority_lock_originator
- id: '1771331444049'
  alias: Send lock timer to loxone
  description: ''
  use_blueprint:
    path: mine/loxone_inputs.yaml
    input:
      target_entities:
      - sensor.dach_links_priority_lock_timer
      - sensor.dach_rechts_priority_lock_timer
      value_template: '{% if value == ''unknown'' %}0{% else %}{{ value }}{% endif
        %}'
- id: '1771534982149'
  alias: Dach tilt to Loxone
  description: ''
  use_blueprint:
    path: mine/loxone_inputs.yaml
    input:
      target_entities:
      - cover.dach_links
      - cover.dach_rechts
      attribute_name: current_tilt_position
      value_template: '{{ value }}'
- id: '1776801083533'
  alias: Send Pergola Automation to Loxone
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.pergola_automatic_enabled
  conditions: []
  actions:
  - action: rest_command.send_to_loxone
    metadata: {}
    data:
      input_name: pergola_automatic_enabled
      value: '{{ 1 if is_state(''input_boolean.pergola_automatic_enabled'', ''on'')
        else 0 }}'
  mode: single
